# Generated by Django 4.2.9 on 2025-11-10 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google")], default="google", max_length=30
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                ("profile_image", models.TextField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("artist", "Artist"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("token_balance", models.BigIntegerField(default=0)),
                ("bio", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_url", models.TextField()),
                ("processed_image_url", models.TextField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "artworks",
            },
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[("1:1", "1:1"), ("2:2", "2:2"), ("1:2", "1:2")],
                        default="1:1",
                        max_length=10,
                    ),
                ),
                ("seed", models.BigIntegerField(blank=True, null=True)),
                ("consumed_tokens", models.BigIntegerField(default=0)),
                ("result_url", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("retrying", "Retrying"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("generation_progress", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "generations",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("model_path", models.TextField(blank=True, null=True)),
                (
                    "training_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("training", "Training"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("training_log_path", models.TextField(blank=True, null=True)),
                ("training_metric", models.JSONField(blank=True, null=True)),
                ("training_progress", models.JSONField(blank=True, null=True)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("commercial", "Commercial"),
                            ("exclusive", "Exclusive"),
                        ],
                        default="personal",
                        max_length=30,
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("generation_cost_tokens", models.BigIntegerField(default=0)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "styles",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "tags",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["name"],
                        name="idx_tags_name",
                    ),
                    models.Index(
                        fields=["is_active", "-usage_count"], name="idx_tags_active"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StyleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_tags",
                        to="app.style",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_tags",
                        to="app.tag",
                    ),
                ),
            ],
            options={
                "db_table": "style_tags",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount_tokens", models.BigIntegerField()),
                (
                    "price_per_token",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("currency_code", models.CharField(default="KRW", max_length=3)),
                (
                    "provider",
                    models.CharField(
                        choices=[("toss", "Toss")], default="toss", max_length=30
                    ),
                ),
                ("provider_payment_key", models.CharField(max_length=120, unique=True)),
                ("provider_order_id", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("receipt_url", models.TextField(blank=True, null=True)),
                ("card_detail", models.JSONField(blank=True, null=True)),
                ("easy_pay_detail", models.JSONField(blank=True, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchases",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("follow", "Follow"),
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("generation_complete", "Generation Complete"),
                            ("generation_failed", "Generation Failed"),
                            ("style_training_complete", "Style Training Complete"),
                            ("style_training_failed", "Style Training Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=30, null=True)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="app.generation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "likes",
            },
        ),
        migrations.CreateModel(
            name="GenerationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_tags",
                        to="app.generation",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_tags",
                        to="app.tag",
                    ),
                ),
            ],
            options={
                "db_table": "generation_tags",
            },
        ),
        migrations.AddField(
            model_name="generation",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="generations",
                to="app.style",
            ),
        ),
        migrations.AddField(
            model_name="generation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "follows",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app.generation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="app.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="ArtworkTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_tags",
                        to="app.artwork",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_tags",
                        to="app.tag",
                    ),
                ),
            ],
            options={
                "db_table": "artwork_tags",
            },
        ),
        migrations.AddField(
            model_name="artwork",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="app.style",
            ),
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "artist_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("signature_image_url", models.TextField(blank=True, null=True)),
                (
                    "verified_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("earned_token_balance", models.BigIntegerField(default=0)),
                ("follower_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "artists",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.BigIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("generation", "Generation"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_token",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency_code", models.CharField(default="KRW", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True)),
                ("payment_method", models.CharField(default="token", max_length=30)),
                ("refunded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="app.generation",
                    ),
                ),
                (
                    "related_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="app.style",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["sender", "-created_at"], name="idx_transactions_sender"
                    ),
                    models.Index(
                        fields=["receiver", "-created_at"],
                        name="idx_transactions_receiver",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="idx_transactions_type",
                    ),
                    models.Index(
                        fields=["related_style"], name="idx_transactions_style"
                    ),
                    models.Index(
                        fields=["related_generation"],
                        name="idx_transactions_generation",
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="idx_transactions_status"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "transaction_type__in",
                        ["purchase", "generation", "withdrawal", "transfer"],
                    )
                ),
                name="valid_transaction_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["pending", "completed", "failed"])),
                name="valid_transaction_status",
            ),
        ),
        migrations.AddIndex(
            model_name="styletag",
            index=models.Index(fields=["tag"], name="idx_style_tags_tag"),
        ),
        migrations.AddConstraint(
            model_name="styletag",
            constraint=models.UniqueConstraint(
                fields=("style", "tag"), name="unique_style_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="styletag",
            constraint=models.UniqueConstraint(
                fields=("style", "sequence"), name="unique_style_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="style",
            index=models.Index(
                fields=["artist", "is_active"], name="idx_styles_artist"
            ),
        ),
        migrations.AddIndex(
            model_name="style",
            index=models.Index(fields=["training_status"], name="idx_styles_status"),
        ),
        migrations.AddIndex(
            model_name="style",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["is_active", "-created_at"],
                name="idx_styles_active",
            ),
        ),
        migrations.AddIndex(
            model_name="style",
            index=models.Index(
                fields=["-usage_count", "-created_at"], name="idx_styles_usage"
            ),
        ),
        migrations.AddConstraint(
            model_name="style",
            constraint=models.UniqueConstraint(
                fields=("artist", "name"), name="unique_artist_style_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="style",
            constraint=models.CheckConstraint(
                check=models.Q(("generation_cost_tokens__gte", 0)),
                name="generation_cost_tokens_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="style",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "training_status__in",
                        ["pending", "training", "completed", "failed"],
                    )
                ),
                name="valid_training_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="style",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("license_type__in", ["personal", "commercial", "exclusive"])
                ),
                name="valid_license_type",
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["buyer", "-created_at"], name="idx_purchases_buyer"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["status"], name="idx_purchases_status"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["provider_order_id"], name="idx_purchases_order_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_tokens__gt", 0)), name="amount_tokens_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["pending", "authorized", "paid", "failed"])
                ),
                name="valid_purchase_status",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="idx_notifications_recipient",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["actor"], name="idx_notifications_actor"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "type__in",
                        [
                            "follow",
                            "like",
                            "comment",
                            "generation_complete",
                            "generation_failed",
                            "style_training_complete",
                            "style_training_failed",
                        ],
                    )
                ),
                name="valid_notification_type",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["generation"], name="idx_likes_generation"),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["user", "-created_at"], name="idx_likes_user"),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "generation"), name="unique_like"
            ),
        ),
        migrations.AddIndex(
            model_name="generationtag",
            index=models.Index(fields=["tag"], name="idx_generation_tags_tag"),
        ),
        migrations.AddConstraint(
            model_name="generationtag",
            constraint=models.UniqueConstraint(
                fields=("generation", "tag"), name="unique_generation_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtag",
            constraint=models.UniqueConstraint(
                fields=("generation", "sequence"), name="unique_generation_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="generation",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_generations_user"
            ),
        ),
        migrations.AddIndex(
            model_name="generation",
            index=models.Index(
                fields=["style", "status"], name="idx_generations_style"
            ),
        ),
        migrations.AddIndex(
            model_name="generation",
            index=models.Index(fields=["status"], name="idx_generations_status"),
        ),
        migrations.AddIndex(
            model_name="generation",
            index=models.Index(
                condition=models.Q(("is_public", True)),
                fields=["is_public", "-created_at"],
                name="idx_generations_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="generation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["queued", "processing", "retrying", "completed", "failed"],
                    )
                ),
                name="valid_generation_status",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["follower"], name="idx_follows_follower"),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["following"], name="idx_follows_following"),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(("follower", models.F("following")), _negated=True),
                name="no_self_follow",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("follower", "following"), name="unique_follow_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["generation", "-created_at"], name="idx_comments_generation"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="idx_comments_user"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["parent"], name="idx_comments_parent"),
        ),
        migrations.AddIndex(
            model_name="artworktag",
            index=models.Index(fields=["tag"], name="idx_artwork_tags_tag"),
        ),
        migrations.AddConstraint(
            model_name="artworktag",
            constraint=models.UniqueConstraint(
                fields=("artwork", "tag"), name="unique_artwork_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="artworktag",
            constraint=models.UniqueConstraint(
                fields=("artwork", "sequence"), name="unique_artwork_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(fields=["style"], name="idx_artworks_style"),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                condition=models.Q(("is_valid", True)),
                fields=["is_valid"],
                name="idx_artworks_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["user"], name="idx_artists_user_id"),
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.CheckConstraint(
                check=models.Q(("earned_token_balance__gte", 0)),
                name="earned_token_balance_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["provider", "provider_user_id"],
                name="idx_users_provider_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                condition=models.Q(("role", "artist")),
                fields=["role"],
                name="idx_users_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"), name="unique_provider_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("token_balance__gte", 0)),
                name="token_balance_non_negative",
            ),
        ),
    ]
