# Generated by Django 4.2.9 on 2025-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_transaction_type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("earn", "Earn"),
                    ("consume", "Consume"),
                    ("generation", "Generation"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "transaction_type__in",
                        [
                            "purchase",
                            "earn",
                            "consume",
                            "generation",
                            "withdrawal",
                            "transfer",
                        ],
                    )
                ),
                name="valid_transaction_type",
            ),
        ),
    ]
